language: php
# https://docs.travis-ci.com/user/languages/php/#HHVM-versions-on-Trusty
dist: trusty
sudo: required
group: edge
 
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm
 
before_script:
  - composer self-update
  - composer install
  - if [[ "$TRAVIS_PHP_VERSION" != '7.2' ]]; then composer require phpunit/phpunit 4.8.35; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.2' ]]; then composer require phpunit/phpunit 6.5.5; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then composer require satooshi/php-coveralls:1.* -n ; fi
 
script:
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then vendor/bin/phpunit; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then vendor/bin/phpcs src/; fi

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then php vendor/bin/coveralls --coverage_clover=clover.xml -v ; fi
