version: 2.1

jobs:
  build:
    parameters:
      php-version:
        type: string
    docker:
      - image: allfunc/pmvc-phpunit:<< parameters.php-version >>
    working_directory: /var/www/app
    steps:
      - checkout
      - run:
          name: "Display information"
          command: |
            date
            php -v
            php -m
            php -r "if(function_exists('gd_info'))print_r(gd_info());"
            composer --version
            phpunit --version
            cat /etc/os-release
            cat /etc/alpine-release
      - run:
          name: Composer install packages
          command: |
            composer update
            composer install --prefer-source
      - run:
          name: PHPUnit
          ###
          # ENABLE_COVERAGE
          # 1. get coveralls repo token (COVERALLS_REPO_TOKEN)
          # https://coveralls.io/github/pmvc/pmvc/settings
          # 2. Update Environment "COVERALLS_REPO_TOKEN"
          ###
          command: |
            ENABLE_COVERAGE=true
            if [ "<< parameters.php-version >>" == "8.2" ]; then
              if [ "$ENABLE_COVERAGE" == "true" ]; then
                XDEBUG_MODE=coverage phpunit --coverage-clover clover.xml
                vendor/bin/phpcs src/
                coveralls --coverage_clover=clover.xml -v -o coveralls-upload.json
              else
                phpunit --display-deprecations
              fi
            else
              phpunit
            fi
      - store_artifacts:
          path: /var/www/app/clover.xml
      - store_artifacts:
          path: /var/www/app/coveralls-upload.json
      - store_test_results:
          path: /tmp/test_output

workflows:
  run-job:
    jobs:
      - build:
          matrix:
            parameters:
              php-version:
                ["8.2", "8.1", "8.0", "7.4", "7.3", "7.2", "7.1", "7.0", "5.6"]
