version: 2.1

jobs:
  unittest:
    parameters:
      php-version:
        type: string
    docker:
      - image: hillliu/pmvc-phpunit:<< parameters.php-version >>
    steps:
      - checkout
      - run:
          name: "Display information"
          command: |
            date
            php -v
            php -m
            composer --version
            phpunit --version
      - run:
          name: Composer install packages
          command: |
            composer update
            composer install --prefer-source
      - run:
          name: PHPUnit
          command: phpunit

workflows:
  run-job:
    jobs:
      - unittest:
          matrix:
            name: test-<< matrix.php-version >>
            parameters:
              php-version: ["8", "7.4"]
