version: 2.1

jobs:
  unittest:
    parameters:
      php-version:
        type: string
    docker:
      - image: hillliu/pmvc-phpunit:<< parameters.php-version >>
    steps:
      - checkout
      - run:
          name: "Display information"
          command: |
            date
            php -v
            php -m
            composer --version
            phpunit --version
      - run:
          name: Composer install packages
          command: |
            composer update
            composer install --prefer-source
            if [[ "<< parameters.php-version >>" == '5.6' ]]; then \
              composer require satooshi/php-coveralls:1.* -n ; \ 
            fi
      - run:
          name: PHPUnit
          command: |
            if [[ "<< parameters.php-version >>" == '5.6' ]]; then \
              phpunit -v --coverage-clover clover.xml; \ 
              vendor/bin/phpcs src/; \ 
            else \
              phpunit \
            fi

workflows:
  run-job:
    jobs:
      - unittest:
          matrix:
            name: test-<< matrix.php-version >>
            parameters:
              php-version: ["8", "5.6"]
